/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class AccessType {
  public static final AccessType eAccessNone = new AccessType("eAccessNone");
  public static final AccessType eAccessPublic = new AccessType("eAccessPublic");
  public static final AccessType eAccessPrivate = new AccessType("eAccessPrivate");
  public static final AccessType eAccessProtected = new AccessType("eAccessProtected");
  public static final AccessType eAccessPackage = new AccessType("eAccessPackage");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AccessType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AccessType value : swigValues)
      if (value.swigValue == swigValue)
        return value;
    throw new IllegalArgumentException("No enum " + AccessType.class + " with value " + swigValue);
  }

  private AccessType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AccessType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AccessType(String swigName, AccessType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AccessType[] swigValues = { eAccessNone, eAccessPublic, eAccessPrivate, eAccessProtected, eAccessPackage };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

