/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class ErrorType {
  public static final ErrorType eErrorTypeInvalid = new ErrorType("eErrorTypeInvalid");
  public static final ErrorType eErrorTypeGeneric = new ErrorType("eErrorTypeGeneric");
  public static final ErrorType eErrorTypeMachKernel = new ErrorType("eErrorTypeMachKernel");
  public static final ErrorType eErrorTypePOSIX = new ErrorType("eErrorTypePOSIX");
  public static final ErrorType eErrorTypeExpression = new ErrorType("eErrorTypeExpression");
  public static final ErrorType eErrorTypeWin32 = new ErrorType("eErrorTypeWin32");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ErrorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (ErrorType value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + ErrorType.class + " with value " + swigValue);
  }

  private ErrorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ErrorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ErrorType(String swigName, ErrorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ErrorType[] swigValues = { eErrorTypeInvalid, eErrorTypeGeneric, eErrorTypeMachKernel, eErrorTypePOSIX, eErrorTypeExpression, eErrorTypeWin32 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

