/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class ExpressionResults {
  public static final ExpressionResults eExpressionCompleted = new ExpressionResults("eExpressionCompleted", lldbJNI.eExpressionCompleted_get());
  public static final ExpressionResults eExpressionSetupError = new ExpressionResults("eExpressionSetupError");
  public static final ExpressionResults eExpressionParseError = new ExpressionResults("eExpressionParseError");
  public static final ExpressionResults eExpressionDiscarded = new ExpressionResults("eExpressionDiscarded");
  public static final ExpressionResults eExpressionInterrupted = new ExpressionResults("eExpressionInterrupted");
  public static final ExpressionResults eExpressionHitBreakpoint = new ExpressionResults("eExpressionHitBreakpoint");
  public static final ExpressionResults eExpressionTimedOut = new ExpressionResults("eExpressionTimedOut");
  public static final ExpressionResults eExpressionResultUnavailable = new ExpressionResults("eExpressionResultUnavailable");
  public static final ExpressionResults eExpressionStoppedForDebug = new ExpressionResults("eExpressionStoppedForDebug");
  public static final ExpressionResults eExpressionThreadVanished = new ExpressionResults("eExpressionThreadVanished");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ExpressionResults swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (ExpressionResults value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + ExpressionResults.class + " with value " + swigValue);
  }

  private ExpressionResults(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ExpressionResults(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ExpressionResults(String swigName, ExpressionResults swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ExpressionResults[] swigValues = { eExpressionCompleted, eExpressionSetupError, eExpressionParseError, eExpressionDiscarded, eExpressionInterrupted, eExpressionHitBreakpoint, eExpressionTimedOut, eExpressionResultUnavailable, eExpressionStoppedForDebug, eExpressionThreadVanished };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

