/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class FrameComparison {
  public static final FrameComparison eFrameCompareInvalid = new FrameComparison("eFrameCompareInvalid");
  public static final FrameComparison eFrameCompareUnknown = new FrameComparison("eFrameCompareUnknown");
  public static final FrameComparison eFrameCompareEqual = new FrameComparison("eFrameCompareEqual");
  public static final FrameComparison eFrameCompareSameParent = new FrameComparison("eFrameCompareSameParent");
  public static final FrameComparison eFrameCompareYounger = new FrameComparison("eFrameCompareYounger");
  public static final FrameComparison eFrameCompareOlder = new FrameComparison("eFrameCompareOlder");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FrameComparison swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (FrameComparison value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + FrameComparison.class + " with value " + swigValue);
  }

  private FrameComparison(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FrameComparison(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FrameComparison(String swigName, FrameComparison swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FrameComparison[] swigValues = { eFrameCompareInvalid, eFrameCompareUnknown, eFrameCompareEqual, eFrameCompareSameParent, eFrameCompareYounger, eFrameCompareOlder };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

