/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class RegisterKind {
  public static final RegisterKind eRegisterKindEHFrame = new RegisterKind("eRegisterKindEHFrame", lldbJNI.eRegisterKindEHFrame_get());
  public static final RegisterKind eRegisterKindDWARF = new RegisterKind("eRegisterKindDWARF");
  public static final RegisterKind eRegisterKindGeneric = new RegisterKind("eRegisterKindGeneric");
  public static final RegisterKind eRegisterKindProcessPlugin = new RegisterKind("eRegisterKindProcessPlugin");
  public static final RegisterKind eRegisterKindLLDB = new RegisterKind("eRegisterKindLLDB");
  public static final RegisterKind kNumRegisterKinds = new RegisterKind("kNumRegisterKinds");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RegisterKind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (RegisterKind value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + RegisterKind.class + " with value " + swigValue);
  }

  private RegisterKind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RegisterKind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RegisterKind(String swigName, RegisterKind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RegisterKind[] swigValues = { eRegisterKindEHFrame, eRegisterKindDWARF, eRegisterKindGeneric, eRegisterKindProcessPlugin, eRegisterKindLLDB, kNumRegisterKinds };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

