/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class ReturnStatus {
  public static final ReturnStatus eReturnStatusInvalid = new ReturnStatus("eReturnStatusInvalid");
  public static final ReturnStatus eReturnStatusSuccessFinishNoResult = new ReturnStatus("eReturnStatusSuccessFinishNoResult");
  public static final ReturnStatus eReturnStatusSuccessFinishResult = new ReturnStatus("eReturnStatusSuccessFinishResult");
  public static final ReturnStatus eReturnStatusSuccessContinuingNoResult = new ReturnStatus("eReturnStatusSuccessContinuingNoResult");
  public static final ReturnStatus eReturnStatusSuccessContinuingResult = new ReturnStatus("eReturnStatusSuccessContinuingResult");
  public static final ReturnStatus eReturnStatusStarted = new ReturnStatus("eReturnStatusStarted");
  public static final ReturnStatus eReturnStatusFailed = new ReturnStatus("eReturnStatusFailed");
  public static final ReturnStatus eReturnStatusQuit = new ReturnStatus("eReturnStatusQuit");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ReturnStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (ReturnStatus value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + ReturnStatus.class + " with value " + swigValue);
  }

  private ReturnStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ReturnStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ReturnStatus(String swigName, ReturnStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ReturnStatus[] swigValues = { eReturnStatusInvalid, eReturnStatusSuccessFinishNoResult, eReturnStatusSuccessFinishResult, eReturnStatusSuccessContinuingNoResult, eReturnStatusSuccessContinuingResult, eReturnStatusStarted, eReturnStatusFailed, eReturnStatusQuit };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

