/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class SearchDepth {
  public static final SearchDepth eSearchDepthInvalid = new SearchDepth("eSearchDepthInvalid", lldbJNI.eSearchDepthInvalid_get());
  public static final SearchDepth eSearchDepthTarget = new SearchDepth("eSearchDepthTarget");
  public static final SearchDepth eSearchDepthModule = new SearchDepth("eSearchDepthModule");
  public static final SearchDepth eSearchDepthCompUnit = new SearchDepth("eSearchDepthCompUnit");
  public static final SearchDepth eSearchDepthFunction = new SearchDepth("eSearchDepthFunction");
  public static final SearchDepth eSearchDepthBlock = new SearchDepth("eSearchDepthBlock");
  public static final SearchDepth eSearchDepthAddress = new SearchDepth("eSearchDepthAddress");
  public static final SearchDepth kLastSearchDepthKind = new SearchDepth("kLastSearchDepthKind", lldbJNI.kLastSearchDepthKind_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SearchDepth swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (SearchDepth value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + SearchDepth.class + " with value " + swigValue);
  }

  private SearchDepth(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SearchDepth(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SearchDepth(String swigName, SearchDepth swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SearchDepth[] swigValues = { eSearchDepthInvalid, eSearchDepthTarget, eSearchDepthModule, eSearchDepthCompUnit, eSearchDepthFunction, eSearchDepthBlock, eSearchDepthAddress, kLastSearchDepthKind };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

