/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class SymbolType {
  public static final SymbolType eSymbolTypeAny = new SymbolType("eSymbolTypeAny", lldbJNI.eSymbolTypeAny_get());
  public static final SymbolType eSymbolTypeInvalid = new SymbolType("eSymbolTypeInvalid", lldbJNI.eSymbolTypeInvalid_get());
  public static final SymbolType eSymbolTypeAbsolute = new SymbolType("eSymbolTypeAbsolute");
  public static final SymbolType eSymbolTypeCode = new SymbolType("eSymbolTypeCode");
  public static final SymbolType eSymbolTypeResolver = new SymbolType("eSymbolTypeResolver");
  public static final SymbolType eSymbolTypeData = new SymbolType("eSymbolTypeData");
  public static final SymbolType eSymbolTypeTrampoline = new SymbolType("eSymbolTypeTrampoline");
  public static final SymbolType eSymbolTypeRuntime = new SymbolType("eSymbolTypeRuntime");
  public static final SymbolType eSymbolTypeException = new SymbolType("eSymbolTypeException");
  public static final SymbolType eSymbolTypeSourceFile = new SymbolType("eSymbolTypeSourceFile");
  public static final SymbolType eSymbolTypeHeaderFile = new SymbolType("eSymbolTypeHeaderFile");
  public static final SymbolType eSymbolTypeObjectFile = new SymbolType("eSymbolTypeObjectFile");
  public static final SymbolType eSymbolTypeCommonBlock = new SymbolType("eSymbolTypeCommonBlock");
  public static final SymbolType eSymbolTypeBlock = new SymbolType("eSymbolTypeBlock");
  public static final SymbolType eSymbolTypeLocal = new SymbolType("eSymbolTypeLocal");
  public static final SymbolType eSymbolTypeParam = new SymbolType("eSymbolTypeParam");
  public static final SymbolType eSymbolTypeVariable = new SymbolType("eSymbolTypeVariable");
  public static final SymbolType eSymbolTypeVariableType = new SymbolType("eSymbolTypeVariableType");
  public static final SymbolType eSymbolTypeLineEntry = new SymbolType("eSymbolTypeLineEntry");
  public static final SymbolType eSymbolTypeLineHeader = new SymbolType("eSymbolTypeLineHeader");
  public static final SymbolType eSymbolTypeScopeBegin = new SymbolType("eSymbolTypeScopeBegin");
  public static final SymbolType eSymbolTypeScopeEnd = new SymbolType("eSymbolTypeScopeEnd");
  public static final SymbolType eSymbolTypeAdditional = new SymbolType("eSymbolTypeAdditional");
  public static final SymbolType eSymbolTypeCompiler = new SymbolType("eSymbolTypeCompiler");
  public static final SymbolType eSymbolTypeInstrumentation = new SymbolType("eSymbolTypeInstrumentation");
  public static final SymbolType eSymbolTypeUndefined = new SymbolType("eSymbolTypeUndefined");
  public static final SymbolType eSymbolTypeObjCClass = new SymbolType("eSymbolTypeObjCClass");
  public static final SymbolType eSymbolTypeObjCMetaClass = new SymbolType("eSymbolTypeObjCMetaClass");
  public static final SymbolType eSymbolTypeObjCIVar = new SymbolType("eSymbolTypeObjCIVar");
  public static final SymbolType eSymbolTypeReExported = new SymbolType("eSymbolTypeReExported");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SymbolType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (SymbolType value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + SymbolType.class + " with value " + swigValue);
  }

  private SymbolType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SymbolType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SymbolType(String swigName, SymbolType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SymbolType[] swigValues = { eSymbolTypeAny, eSymbolTypeInvalid, eSymbolTypeAbsolute, eSymbolTypeCode, eSymbolTypeResolver, eSymbolTypeData, eSymbolTypeTrampoline, eSymbolTypeRuntime, eSymbolTypeException, eSymbolTypeSourceFile, eSymbolTypeHeaderFile, eSymbolTypeObjectFile, eSymbolTypeCommonBlock, eSymbolTypeBlock, eSymbolTypeLocal, eSymbolTypeParam, eSymbolTypeVariable, eSymbolTypeVariableType, eSymbolTypeLineEntry, eSymbolTypeLineHeader, eSymbolTypeScopeBegin, eSymbolTypeScopeEnd, eSymbolTypeAdditional, eSymbolTypeCompiler, eSymbolTypeInstrumentation, eSymbolTypeUndefined, eSymbolTypeObjCClass, eSymbolTypeObjCMetaClass, eSymbolTypeObjCIVar, eSymbolTypeReExported };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

