/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class SymbolContextItem {
  public static final SymbolContextItem eSymbolContextTarget = new SymbolContextItem("eSymbolContextTarget", lldbJNI.eSymbolContextTarget_get());
  public static final SymbolContextItem eSymbolContextModule = new SymbolContextItem("eSymbolContextModule", lldbJNI.eSymbolContextModule_get());
  public static final SymbolContextItem eSymbolContextCompUnit = new SymbolContextItem("eSymbolContextCompUnit", lldbJNI.eSymbolContextCompUnit_get());
  public static final SymbolContextItem eSymbolContextFunction = new SymbolContextItem("eSymbolContextFunction", lldbJNI.eSymbolContextFunction_get());
  public static final SymbolContextItem eSymbolContextBlock = new SymbolContextItem("eSymbolContextBlock", lldbJNI.eSymbolContextBlock_get());
  public static final SymbolContextItem eSymbolContextLineEntry = new SymbolContextItem("eSymbolContextLineEntry", lldbJNI.eSymbolContextLineEntry_get());
  public static final SymbolContextItem eSymbolContextSymbol = new SymbolContextItem("eSymbolContextSymbol", lldbJNI.eSymbolContextSymbol_get());
  public static final SymbolContextItem eSymbolContextEverything = new SymbolContextItem("eSymbolContextEverything", lldbJNI.eSymbolContextEverything_get());
  public static final SymbolContextItem eSymbolContextVariable = new SymbolContextItem("eSymbolContextVariable", lldbJNI.eSymbolContextVariable_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SymbolContextItem swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
      for (SymbolContextItem value : swigValues)
          if (value.swigValue == swigValue)
              return value;
    throw new IllegalArgumentException("No enum " + SymbolContextItem.class + " with value " + swigValue);
  }

  private SymbolContextItem(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SymbolContextItem(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SymbolContextItem(String swigName, SymbolContextItem swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SymbolContextItem[] swigValues = { eSymbolContextTarget, eSymbolContextModule, eSymbolContextCompUnit, eSymbolContextFunction, eSymbolContextBlock, eSymbolContextLineEntry, eSymbolContextSymbol, eSymbolContextEverything, eSymbolContextVariable };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

